### ISSUE TITLE
Att 2

### ISSUE THREAD

**Issue by Chu127001** [Chu127001/prodTest#2]

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 0.01
Contract address: [0x7d65f341d697d4f5e5135aadfffd3d94a0fc64d2](https://etherscan.io/address/0x7d65f341d697d4f5e5135aadfffd3d94a0fc64d2)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: churik
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
